"""Rename Singleton table to Count

Revision ID: 385ff87ef25f
Revises: 4bc4b357ac7b
Create Date: 2024-02-14 14:57:26.013174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385ff87ef25f'
down_revision = '4bc4b357ac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    # ### end Alembic commands ###
