"""Add queue column to Count table

Revision ID: f853b389a1d8
Revises: 385ff87ef25f
Create Date: 2024-02-14 15:00:36.023576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f853b389a1d8'
down_revision = '385ff87ef25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('count', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('count', schema=None) as batch_op:
        batch_op.drop_column('queue')

    # ### end Alembic commands ###
